version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./www:/app
        depends_on:
            - php-fpm
        networks:
          psr-project:
                ipv4_address: 10.5.0.105
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./www:/app
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=mysql"
        depends_on:
            - mysql
        networks:
          psr-project:

    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./www:/app
        depends_on:
            - mysql

        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        tty: true

        networks:
          psr-project:

    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=psr"

        networks:
            psr-project:
              ipv4_address: 10.5.0.106



networks:
  psr-project:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24